### ISSUE TITLE
User can create new Task without an active List selected

### ISSUE THREAD

**Issue by johnabed** [Devstackr/task-manager-mean-stack#2]
Source: task-view.component.html
```
<button routerLink="./new-task" class="circle-add-button button is-primary">
  <img src="../../../assets/plus-icon.svg" class="has-text-white">
</button>
```
There is no enable/disable feature which stops the user from pressing new-task, which then changes the URL to /lists/new-task, routing the user back to TaskViewComponent. Pressing again, they route to /lists/new-task/new-task and can enter a new Task for an undefined List with the id of "new-task".

Suggested solution:
`<button class="button circle-add-button is-primary" routerLink="./new-task" [disabled]="!listSelected">`

```
ngOnInit() {
    this.route.params.subscribe((params: Params) => {
      this.taskService.getTasks(params.listId).subscribe((tasks: Task[]) => {
          this.tasks = tasks;
          this.listSelected = true;
        })
    });
```

**Comment by johnabed** [comment]
See following commit for required changes (personal branch)
https://github.com/johnabed/task-manager-mean/commit/bacecf93a9295fa836a31f8e53c829f6d44f556a

**Comment by Devstackr8** [comment]
@johnabed Thanks for the creating the issue.

I have just double checked and when the New Task button is pressed it is supposed to navigate to the '/new-task' url, not '/lists/new-task'.
I see you have closed this issue so maybe you found the underlying issue and fixed that, but let me know if there is anything I can do to help.

Andy
